force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Books</fullName>
            </value>
            <value>
                <fullName>Groceries</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product_Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProductCatalogControllerTest.cls
@isTest
private class ProductCatalogControllerTest {

    @isTest
    static void testGetActiveProducts() {

        Product__c p1 = new Product__c(
            Name='Laptop',
            Product_Code__c='P001',
            Category__c='Electronics',
            Price__c=50000,
            Quantity__c=10,
            Active__c=true
        );

        Product__c p2 = new Product__c(
            Name='Mobile',
            Product_Code__c='P002',
            Category__c='Electronics',
            Price__c=20000,
            Quantity__c=5,
            Active__c=false
        );

        insert new List<Product__c>{p1,p2};

        Test.startTest();

        List<Product__c> products =
            ProductCatalogController.getActiveProducts();

        Test.stopTest();

        System.assertEquals(1, products.size());
        System.assertEquals('Laptop', products[0].Name);
    }
}